In [4]:
import cv2
import numpy as np

# Erosion

In [36]:
img = cv2.imread('erosion.png', 0)
kernel = np.ones((9,9), np.uint8)
erosion = cv2.erode(img, kernel, iterations = 1)

In [28]:
cv2.imshow('img', img)
cv2.imshow('ero', erosion)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Dilation

In [29]:
dilation = cv2.dilate(img, kernel, iterations = 1)

In [30]:
cv2. imshow('dil', dilation)
cv2.waitKey(2000)
cv2.destroyAllWindows()

# Opening and Closing

In [31]:
opening = cv2.morphologyEx(img, cv2.MORPH_OPEN, kernel)
closing = cv2.morphologyEx(img, cv2.MORPH_CLOSE, kernel)

In [33]:
cv2.imshow('img', img)
cv2.imshow('opn', opening)
cv2.imshow('clo', closing)
cv2.waitKey(2000)
cv2.destroyAllWindows()

# Morphological Gradient

In [34]:
gradient = cv2.morphologyEx(img, cv2.MORPH_GRADIENT, kernel)

In [35]:
cv2.imshow('img', img)
cv2.imshow('grd', gradient)
cv2.waitKey(5000)
cv2.destroyAllWindows()

# Top hat and Black hat

In [37]:
open2 = cv2.morphologyEx(img, cv2.MORPH_OPEN, kernel)
close2 = cv2.morphologyEx(img, cv2.MORPH_CLOSE, kernel)
tophat = cv2.morphologyEx(img, cv2.MORPH_TOPHAT, kernel)
blackhat = cv2.morphologyEx(img, cv2.MORPH_BLACKHAT, kernel)

In [40]:
cv2.imshow('img', img)
cv2.imshow('opn', open2)
cv2.imshow('clo', close2)
cv2.imshow('tph', tophat)
cv2.imshow('blh', blackhat)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Structuring kernel

In [41]:
cv2.getStructuringElement(cv2.MORPH_RECT, (5,5))

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

In [42]:
cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5,5))

array([[0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0]], dtype=uint8)

In [43]:
kernel2 = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (5,5))

In [44]:
kernel2

array([[0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0]], dtype=uint8)

In [47]:
erosion = cv2.erode(img, kernel2, iterations = 1)

In [48]:
cv2.imshow('ero', erosion)
cv2.waitKey(0)
cv2.destroyAllWindows()